## The creation of tensors

In [19]:
%load_ext lab_black

In [20]:
import torch
import numpy as np

In [21]:
a = torch.FloatTensor(2, 3, 2)

In [22]:
a.zero_()

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [23]:
torch.FloatTensor([[1, 2, 3], [3, 2, 1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [24]:
n = np.zeros(shape=(3, 2))

In [26]:
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
# Accept numpy array
b = torch.tensor(n)

In [28]:
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [30]:
# Set type
n = np.zeros(shape=(3, 2), dtype=np.float32)

In [32]:
tmp = torch.tensor(n)

In [33]:
tmp

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [34]:
tmp.dtype

torch.float32

In [35]:
# torch type
n = np.zeros(shape=(3, 2))

In [36]:
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Scalar tensors

In [38]:
a = torch.tensor([1, 2, 3])

In [39]:
a

tensor([1, 2, 3])

In [40]:
s = a.sum()

In [41]:
s

tensor(6)

In [42]:
s.item()

6

### GPU tensors

In [44]:
a = torch.FloatTensor([2, 3])

In [46]:
ca = a.to("cuda")

In [47]:
ca

tensor([2., 3.], device='cuda:0')

In [48]:
a + 1

tensor([3., 4.])

In [49]:
ca + 1

tensor([3., 4.], device='cuda:0')

## Gradients

In [63]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)

In [64]:
v2 = torch.tensor([2.0, 2.0])

In [65]:
v_sum = v1 + v2

In [66]:
v_res = (v_sum * 2).sum()

In [67]:
v_res

tensor(12., grad_fn=<SumBackward0>)

In [68]:
v1.is_leaf, v2.is_leaf

(True, True)

In [70]:
v1.requires_grad, v2.requires_grad

(True, False)

In [71]:
v_sum.requires_grad

True

In [72]:
v_res.backward()

In [73]:
v1.grad

tensor([2., 2.])

아래 코드는 다음과 같당


$v_{sum} =  x_1^3 + x_2^2 $


$v_{sum}' =  3x_1^2 + 2x_2$

In [89]:
## Test
x1 = torch.tensor([2.0, 2.0], requires_grad=True)
x2 = torch.tensor([3.0, 2.0])

v = x1**x2
v_sum = v.sum()

In [90]:
v_sum.backward()

In [91]:
x1.grad

tensor([12.,  4.])

## NN Building blocks

In [92]:
import torch.nn as nn

In [93]:
l = nn.Linear(2, 5)
v = torch.FloatTensor([1, 2])

In [95]:
# 1x2 @ 2x5 -> 1x5
l(v)

tensor([-0.2336,  1.0521,  0.5279, -1.1393, -0.4394], grad_fn=<AddBackward0>)

In [97]:
s = nn.Sequential(
    nn.Linear(2, 5),
    nn.ReLU(),
    nn.Linear(5, 20),
    nn.ReLU(),
    nn.Linear(20, 10),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1),
)

In [98]:
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3, inplace=False)
  (6): Softmax(dim=1)
)

In [100]:
result = s(torch.FloatTensor([[1, 2]]))

In [102]:
result.shape

torch.Size([1, 10])

In [103]:
result

tensor([[0.1110, 0.0854, 0.0989, 0.0872, 0.1296, 0.0989, 0.1558, 0.0884, 0.0460,
         0.0989]], grad_fn=<SoftmaxBackward0>)

## TensorboardX

In [104]:
%load_ext tensorboard

In [105]:
import math
from tensorboardX import SummaryWriter

In [106]:
if __name__ == "__main__":
    writer = SummaryWriter()
    func = {"sin": math.sin, "cos": math.cos, "tan": math.tan}
    for angle in range(-360, 360):
        angle_rad = angle * math.pi / 180 
        for name, fun in func.items():
            val = fun(angle_rad)
            writer.add_scalar(name, val, angle)